name: Initial setup
description: Setup conda and system environments to run tests

inputs:
    conda_env:
        required: true
        type: string
        description: Name of conda env
    compiler:
        required: true
        type: string
        description: Compiler used for execution

env:
    conda_yaml_fille: tests/conda-envs/${{ inputs.conda_env }}.yaml

runs:
    using: composite
    steps:
        - name: Get Date
          id: get-date
          run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
          shell: bash

        - name: Restore Conda env cache
          id: conda-cache
          uses: actions/cache@v3
          with:
            path: ${{ conda_yaml_fille }}
            key: conda-${{ inputs.conda_env }}-${{ hashFiles(conda_yaml_fille) }}-${{ steps.get-date.outputs.today }}

        - uses: conda-incubator/setup-miniconda@v2
          with:
              miniforge-variant: Mambaforge
              auto-update-conda: true
              use-mamba: true
              environment-file: ${{ conda_yaml_fille }}
              activate-environment: ${{ inputs.conda_env }}-test

        - uses: ./.github/actions/build_mlir
          if: ${{ inputs.conda_env == 'mlir' }}

        - name: Install compiler for dynamo
          shell: bash -el {0}
          run: |
              sudo apt-get update
              sudo apt-get install -y build-essential
          if: ${{ inputs.compiler == 'dynamo' }}

        - name: Setup benchmarks package
          shell: bash -el {0}
          run: |
              pip install -e .
