name: Initial setup
description: Setup conda and system environments to run tests

inputs:
    conda_env:
        required: true
        type: string
        description: Name of conda env
    compiler:
        required: true
        type: string
        description: Compiler used for execution

runs:
    using: composite
    env:
        CONDA_YAML_FILE: tests/conda-envs/${{ inputs.conda_env }}.yaml
        CONDA_ENV_NAME: ${{ inputs.conda_env }}-test
    steps:
        - uses: conda-incubator/setup-miniconda@v2
          with:
              miniforge-variant: Mambaforge
              miniforge-version: latest
              use-mamba: true
              activate-environment: ${{ env.CONDA_ENV_NAME }}

        - name: Get Date
          id: get-date
          run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
          shell: bash

        - name: Restore Conda env cache
          id: conda-cache
          uses: actions/cache@v3
          env:
              # Increase this value to reset cache if etc/example-environment.yml has not changed
              CACHE_NUMBER: 0
          with:
              path: ${{ env.CONDA }}/envs
              key: conda-${{ inputs.conda_env }}-${{ hashFiles(env.CONDA_YAML_FILE) }}-${{ steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER }}

        - name: Update conda env
          if: steps.conda-cache.outputs.cache-hit != 'true'
          shell: bash -el {0}
          run: mamba env update -n ${{ env.CONDA_ENV_NAME }} -f ${{ env.CONDA_YAML_FILE }}

        - uses: ./.github/actions/build_mlir
          if: ${{ inputs.conda_env == 'mlir' }}

        - name: Install compiler for dynamo
          shell: bash -el {0}
          run: |
              sudo apt-get update
              sudo apt-get install -y build-essential
          if: ${{ inputs.compiler == 'dynamo' }}

        - name: Setup benchmarks package
          shell: bash -el {0}
          run: pip install -e .
