name: Build torch-mlir
description: Checkout torch-mlir repo and build it in mlir-test conda env

runs:
    using: composite
    steps:
        - name: Checkout torch-mlir repo
          uses: actions/checkout@v4
          with:
              repository: intel-ai/torch-mlir
              path: torch-mlir
              ref: 'cpu-proto'
              submodules: recursive
        - name: Build torch-mlir
          shell: bash -el {0}
          run: |
              source /opt/intel/oneapi/setvars.sh
              tests/scripts/build-mlir.sh torch-mlir
              echo PYTHONPATH=`pwd`/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir:`pwd`/torch-mlir/examples:$PYTHONPATH >> $GITHUB_ENV
              echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> $GITHUB_ENV
