name: Build torch-mlir
description: Checkout torch-mlir repo and build it in mlir-test conda env

runs:
    using: composite
    steps:
        - name: Checkout torch-mlir repo
          uses: actions/checkout@v4
          with:
              repository: intel-ai/torch-mlir
              path: torch-mlir
              ref: 'cpu-proto'
              submodules: recursive

        - name: Install system and Intel packages
          shell: bash -el {0}
          run: |
              curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
              echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
              sudo apt-get update
              sudo apt-get install -y build-essential intel-basekit

        - name: Build torch-mlir
          shell: bash -el {0}
          run: |
              source /opt/intel/oneapi/setvars.sh
              tests/scripts/build-mlir.sh torch-mlir
              echo PYTHONPATH=`pwd`/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir:`pwd`/torch-mlir/examples:$PYTHONPATH >> $GITHUB_ENV
              echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH >> $GITHUB_ENV

        - name: Upload built mlir
          uses: actions/upload-artifact@v3
              name: torch-mlir-binary
              path: torch-mlir/
              if-no-files-found: error
