name: Run mlp test on requested platforms

on:
    workflow_call:
        inputs:
            compiler:
                required: true
                type: string
                description: Type of JIT to use
            device:
                required: true
                type: string
                description: Type of engine to use
            tag:
                required: true
                type: string
                description: Tag to label this result in DB
            torch_mlir_repo:
                description: Torch-MLIR repository on github
                required: true
                default: intel-ai/torch-mlir
                type: string
            torch_mlir_branch:
                description: Torch-MLIR branch to checkout
                required: true
                default: cpu-proto
                type: string
            runner_type:
                description: Type of runner to use
                required: true
                default: spr
                type: string
            shutdown_cloud_runner:
                description: Whether to shutdown AWS cloud runner
                required: false
                default: true
                type: boolean
            test_script:
                description: Test script to run
                required: false
                default: "./mlp.sh"
                type: string
        secrets:
            DB_URL:
                required: true

jobs:
    print_inputs:
        runs-on: Linux
        steps:
            - name: Print Inputs
              run: echo "${{ toJSON(github.event.inputs) }}"

    get_runner_labels:
        runs-on: Linux
        outputs:
            runner_labels: ${{ steps.get_runner_labels.outputs.runner_labels }}
        steps:
            - name: Get runner labels
              id: get_runner_labels
              shell: bash -el {0}
              run: |
                case "${{ inputs.runner_type }}" in
                    spr)
                        echo 'runner_labels=["self-hosted", "spr", "glados"]' >> $GITHUB_OUTPUT;;
                    amd32c)
                        echo 'runner_labels=["self-hosted", "amd32c", "aws"]' >> $GITHUB_OUTPUT;;
                    amd64c)
                        echo 'runner_labels=["self-hosted", "amd64c", "aws"]' >> $GITHUB_OUTPUT;;
                    nvidia)
                        echo 'runner_labels=["self-hosted", "nvidia", "aws"]' >> $GITHUB_OUTPUT;;
                    *)
                        echo "runner_labels=unknown" >> $GITHUB_OUTPUT;;
                esac

    mlp_test:
        needs: get_runner_labels
        runs-on: ${{ fromJSON(needs.get_runner_labels.outputs.runner_labels) }}
        steps:
            - name: Guess conda env from device and compiler parameters
              id: guess_conda_env
              shell: bash -el {0}
              run: |
                case "${{ inputs.compiler }}" in
                    torch_mlir*)
                        echo conda_env=mlir-dev >> $GITHUB_OUTPUT;;
                    ipex*)
                        echo conda_env=ipex >> $GITHUB_OUTPUT;;
                    *)
                        if [[ ${{ inputs.device }} = "cuda" ]]; then
                            echo conda_env=cuda >> $GITHUB_OUTPUT
                        else
                            echo conda_env=cpu >> $GITHUB_OUTPUT
                        fi;;
                esac

            - uses: actions/checkout@v4
            - uses: ./.github/actions/initial_setup
              with:
                  conda_env: ${{ steps.guess_conda_env.outputs.conda_env }}
                  compiler: ${{ inputs.compiler }}
                  torch_mlir_repo: ${{ inputs.torch_mlir_repo }}
                  torch_mlir_branch: ${{ inputs.torch_mlir_branch }}

            - name: Run MLP test on specific compiler
              shell: bash -el {0}
              run: |
                  source ${CONDA}/bin/activate ${{ steps.guess_conda_env.outputs.conda_env }}

                  export ONEDNN_VERBOSE=0
                  LABELS='${{ needs.get_runner_labels.outputs.runner_labels }}'
                  if [[ ${LABELS} = *glados* ]]; then
                      URL="--url ${{ secrets.DB_URL }}"
                  fi

                  export DL_BENCH_ARGS="--host ${{ inputs.runner_type }} --compiler ${{ inputs.compiler }} --device ${{ inputs.device }} --tag ${{ inputs.tag }} -v ${URL}"
                  export KMP_AFFINITY=respect,noreset,granularity=fine,balanced
                  # This parameter is incredibly important once we use numactl to pick one socket, performance difference was 10x for resnet50 bs=1 torch-inductor
                  export OMP_NUM_THREADS=32
                  if [[ ${LABELS} = *glados* ]]; then
                      numactl -N 1 ${{ inputs.test_script }}
                  else
                      source ${{ inputs.test_script}}
                  fi

            - name: Upload results.db to artifacts when running in AWS
              if: contains(fromJSON(needs.get_runner_labels.outputs.runner_labels), 'aws')
              uses: actions/upload-artifact@v3
              with:
                  name: results.db
                  path: results.db

            - name: Shutdown AWS cloud runner
              if: contains(fromJSON(needs.get_runner_labels.outputs.runner_labels), 'aws') && inputs.shutdown_cloud_runner
              shell: bash -el {0}
              run: sudo shutdown -h +2

    parse_results:
        runs-on: [self-hosted, glados, spr]
        needs:
            - get_runner_labels
            - mlp_test
        if: contains(fromJSON(needs.get_runner_labels.outputs.runner_labels), 'aws')
        steps:
            - uses: actions/checkout@v4
            - name: Download results.db from artifacts
              uses: actions/download-artifact@v3
              with:
                  name: results.db
                  path: .

            - name: Upload results into DB
              shell: bash -el {0}
              run: |
                ls -l

                sudo apt update && sudo apt install sqlite3
                ./db_tools/export_sqlite2csv.sh

                source ${CONDA}/bin/activate
                pip install sqlalchemy pandas mysql-connector-python
                pip install --no-deps -e .
                python ./db_tools/export_csv2url.py results.csv --url ${{ secrets.DB_URL }}

