name: Run mlp test on requested platforms

on:
    workflow_call:
        inputs:
            conda_env:
                required: true
                type: string
                description: Name of conda env
            compiler:
                required: true
                type: string
                description: Type of JIT to use
            device:
                required: true
                type: string
                description: Type of engine to use

jobs:
    mlp_test:
        runs-on:
            - self-hosted
            - glados
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/initial_setup
              with:
                  conda_env: ${{ inputs.conda_env }}
                  compiler: ${{ inputs.compiler }}

            - name: Run MLP test on specific compiler
              shell: bash -el {0}
              run: |
                  benchmark-run -c "${{ inputs.compiler }}" -d ${{ inputs.device }} -b mlp -p "name='size2'" -v
              if: ${{ inputs.compiler != 'torch_mlir' }}

            - name: Run MLP test on specific compiler
              shell: bash -el {0}
              run: |
                  source /opt/intel/oneapi/setvars.sh
                  benchmark-run -c "${{ inputs.compiler }}" -d ${{ inputs.device }} -b mlp -p "name='size2'" -v
              if: ${{ inputs.compiler == 'torch_mlir' }}
