name: Run mlp test on requested platforms

on:
    workflow_call:
        inputs:
            conda_env:
                required: true
                type: string
                description: Name of conda env
            compiler:
                required: true
                type: string
                description: Type of JIT to use
            device:
                required: true
                type: string
                description: Type of engine to use
        secrets:
            DB_URL:
                required: true

jobs:
    build_mlir:
        runs-on:
            - self-hosted
            - glados
        steps:
            - uses: actions/checkout@v4
              if: ${{ inputs.conda_env == 'mlir' }}

            - name: Build mlir and upload to artifact storage
              if: ${{ inputs.conda_env == 'mlir' }}
              uses: ./.github/actions/build_mlir
              with:
                  conda_env: ${{ inputs.conda_env }}

    mlp_test:
        runs-on:
            - self-hosted
            - glados
        needs: build_mlir
        strategy:
            matrix:
                bname:
                    - size2
                    - size3
                    - size4
                    - size5
                    - size5_sigm
                    - size5_tanh
                    - size5_gelu
                    - size5_linear
                    - size5_inplace
                    - size5_bn
                    - size5_bn_gelu
                    - size5_drop_gelu
                    - 100@512
                    - 25@1024
                    - 4@16384
                    - 2@16384
                batch_size:
                    - 1024
                include:
                    - {bname: 'size5', batch_size: 1}
                    - {bname: 'size5', batch_size: 16}
                    - {bname: 'size5', batch_size: 256}
                    - {bname: 'size5', batch_size: 2048}
                    - {bname: 'size5', batch_size: 8196}
            fail-fast: false
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/initial_setup
              with:
                  conda_env: ${{ inputs.conda_env }}
                  compiler: ${{ inputs.compiler }}

            - name: Run MLP test on specific compiler
              shell: bash -el {0}
              run: |
                  BATCH_SIZE=$(printf "%04d" ${{ matrix.batch_size }})
                  source ${CONDA}/bin/activate ${{ inputs.conda_env }}
                  benchmark-run \
                    --host spr \
                    --benchmark mlp \
                    -p "name='${{ matrix.bname }}',batch_size=${{ matrix.batch_size }}" \
                    --benchmark_desc "${{ matrix.bname }}_bs${BATCH_SIZE}" \
                    --compiler "${{ inputs.compiler }}" \
                    --device ${{ inputs.device }} \
                    -v --url ${{ secrets.DB_URL }}
