name: Rebuild base docker image for runners

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Docker image tag. Recommended value to use is git hash of main branch and date-time of build.
        type: string
        required: true
        default: 0.0.1
      push:
        description: Push image to DockerHub
        required: true
        type: choice
        options:
          - false
          - true
        default: "false"

env:
  DOCKER_REGISTRY: docker-registry.docker-registry.svc.cluster.local:5000

jobs:
  build:
    runs-on:
      - self-hosted
      - glados
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image ${{ env.DOCKER_REGISTRY }}/graph-compiler-playground-actions-runner:${{ inputs.image_tag }}
        run: |
          cd tests/docker
          docker build . \
            --tag ${{ env.DOCKER_REGISTRY }}/graph-compiler-playground-actions-runner:${{ inputs.image_tag }}

      - name: Push image ${{ env.DOCKER_REGISTRY }}/graph-compiler-playground-actions-runner:${{ inputs.image_tag }}
        if: ${{ inputs.push == 'true' }}
        run: docker push ${{ env.DOCKER_REGISTRY }}/graph-compiler-playground-actions-runner:${{ inputs.image_tag }}
