name: Run MLP test in one configuration

on:
    workflow_dispatch:
        inputs:
            env:
                description: Conda env to use to run the test
                required: true
                default: mlir
                type: choice
                options:
                    - mlir
                    - cpu
                    - ipex
                    - cuda
            device:
                description: Device to use to execute the test
                required: true
                default: cpu
                type: choice
                options:
                    - cpu
                    - xpu
                    - cuda
            compiler:
                description: JIT compiler to use to execute the test
                required: true
                default: torch_mlir
                type: choice
                options:
                    - torch
                    - dynamo
                    - torchscript
                    - torchscript_onednn
                    - ipex
                    - torch_mlir
            tag:
                description: tag to label this run in DB
                required: true
                default: "test"
                type: string

jobs:
    mlp_test:
        uses: ./.github/workflows/mlp-test.yml
        with:
            conda_env: ${{ inputs.env }}
            compiler: ${{ inputs.compiler }}
            device: ${{ inputs.device }}
            tag: ${{ inputs.tag }}
        secrets:
            DB_URL: ${{ secrets.DB_URL }}
