name: Run tests on multiple platforms

on:
    workflow_dispatch:

jobs:
    mlp_test:
        strategy:
            matrix:
                type: [
                  {env: 'cpu', device: 'cpu', compiler: ''},
                  {env: 'cpu', device: 'cpu', compiler: 'dynamo'},
                  {env: 'cpu', device: 'cpu', compiler: 'torchscript'},
                  {env: 'cpu', device: 'cpu', compiler: 'torchscript_onednn'},
                  {env: 'ipex', device: 'cpu', compiler: 'ipex'},
#                  {env: 'ipex', device: 'xpu', compiler: 'ipex'},
                  {env: 'mlir', device: 'cpu', compiler: 'torch_mlir'}
                ]
        uses: ./.github/workflows/mlp-test.yml
        with:
            conda_env: ${{ matrix.type.env }}
            compiler: ${{ matrix.type.compiler }}
            device: ${{ matrix.type.device }}
