name: Run MLP test in one configuration

on:
    workflow_dispatch:
        inputs:
            env:
                description: Conda env to use to run the test
                required: true
                default: mlir
                type: choice
                options:
                    - mlir
                    - cpu
                    - ipex
                    - cuda
            device:
                description: Device to use to execute the test
                required: true
                default: cpu
                type: choice
                options:
                    - cpu
                    - xpu
                    - cuda
            compiler:
                description: JIT compiler to use to execute the test
                required: true
                default: torch_mlir
                type: choice
                options:
                    - dynamo
                    - torchscript
                    - torchscript_onednn
                    - ipex
                    - torch_mlir
            torch_mlir_repo:
                description: Torch-MLIR repository on github
                required: true
                default: intel-ai/torch-mlir
                type: string
            torch_mlir_branch:
                description: Torch-MLIR branch to checkout
                required: true
                default: cpu-proto
                type: string

jobs:
    mlp_test:
        uses: ./.github/workflows/mlp-test.yml
        with:
            conda_env: ${{ inputs.env }}
            compiler: ${{ inputs.compiler }}
            device: ${{ inputs.device }}
            torch_mlir_repo: ${{ inputs.torch_mlir_repo }}
            torch_mlir_branch: ${{ inputs.torch_mlir_branch }}
        secrets:
            DB_URL: ${{ secrets.DB_URL }}
