name: SPR full run

on:
    workflow_dispatch:
        inputs:
            tag:
                description: tag to label this run in DB
                required: true
                default: "test"
            torch_mlir_repo:
                description: Torch-MLIR repository on github
                required: true
                default: intel-ai/torch-mlir
                type: string
            torch_mlir_branch:
                description: Torch-MLIR branch to checkout
                required: true
                default: cpu-proto
            test_scripts:
                description: Test scripts to execute
                required: false
                default: '["./mlp.sh", "./cnn.sh", "./llm.sh"]'
                type: string
    schedule:
        # Runs at 12pm UTC (6am CST) on every Saturday
        - cron: "0 12 * * 6"

jobs:
    print_inputs:
        runs-on: Linux
        steps:
            - name: Print Inputs
              run: echo "${{ toJSON(github.event.inputs) }}"

    mlp_test:
        strategy:
            matrix:
                type: [
                  {device: 'cpu', compiler: 'torch'},
                  {device: 'cpu', compiler: 'dynamo'},
                  {device: 'cpu', compiler: 'torchscript'},
                  {device: 'cpu', compiler: 'torchscript_onednn'},
                  {device: 'cpu', compiler: 'ipex'},
                  {device: 'cpu', compiler: 'ipex_onednn_graph'},
#                  {device: 'xpu', compiler: 'ipex'},
                  {device: 'cpu', compiler: 'torch_mlir'},
                  {device: 'cpu', compiler: 'torch_mlir_xsmm'}
                ]
                test_script: ${{ github.event_name == 'workflow_dispatch' && fromJson(inputs.test_scripts) || fromJson('["./mlp.sh", "./cnn.sh", "./llm.sh"]') }}
            fail-fast: false
        uses: ./.github/workflows/execute-test-script.yml
        with:
            compiler: ${{ matrix.type.compiler }}
            device: ${{ matrix.type.device }}
            tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || 'ci' }}
            torch_mlir_repo: ${{ github.event_name == 'workflow_dispatch' && inputs.torch_mlir_repo || 'intel-ai/torch-mlir' }}
            torch_mlir_branch: ${{ github.event_name == 'workflow_dispatch' && inputs.torch_mlir_branch || 'cpu-proto' }}
            runner_type: spr
            shutdown_cloud_runner: false
            test_script: ${{ matrix.test_script }}
        secrets:
            DB_URL: ${{ secrets.DB_URL }}
